### ISSUE TITLE
Update Today URL

### ISSUE THREAD

**Issue by jmbarne3** [UCF/Main-Site-Theme#170]
**Description**
The today URL needs to be updated to point to the new URL on line [121](https://github.com/UCF/Main-Site-Theme/blob/f6498e8509deed2bf00c40872ea5dc9fb4a97f14/taxonomy-colleges.php#L121) of the colleges taxonomy template.

**Why it's Important**
Redirects are unnecessary when we control the URL.

**Alternatives**
Resistance is futile. 

**Possible Implementation**
Just update the URL...

**Additional context**
Seriously, that's all we need to do...

**Comment by cadieb** [comment]
Resolved in [v3.2.3](https://github.com/UCF/Main-Site-Theme/releases/tag/v3.2.3).
