### ISSUE TITLE
Hide Events Section if No Event Data

### ISSUE THREAD

**Issue by cohpa** [UCF/Main-Site-Theme#202]
**Description**

The query for events with our bldg_id is a smart way to go if you're just trying to convey what events take place at that location, but it doesn't really reflect the events that are hosted by the college in that building. Seems to read that we are inactive vs just lacking event space in our specific building. I can certainly see it from both viewpoints. However, with so many of the locations showing "No events found", it might be nice to just hide that section if there isn't any data to display. 
**Why it's Important**

No one likes empty blocks of content showing on their page and "No events found" shows up on the overwhelming majority. 
**Alternatives**

Possibly consider removing the whole section. Most locations don't appear to be benefiting from this feature. 
**Possible Implementation**

**Additional context**

**Comment by cjg89** [comment]
Hi @cohpa , we recently pushed an update that ensures the events section on location profiles is completely hidden when the given location has no upcoming events to display (see https://github.com/UCF/UCF-Location-CPT-Plugin/pull/21).  Going to mark this issue as closed.
