### ISSUE TITLE
Locations and Admissions Sticky Nav Causes 'Jumps'

### ISSUE THREAD

**Issue by LemondRinds** [UCF/Main-Site-Theme#3]
Heyo! Just wanted to share that the locations and admissions pages with the sticky navs have displacement issues when the nav bars become affixed.
I had a similar problem with bootstrap's affix plugin when applying it to the tbhc theme. When it became affixed, the nav bar would be removed from the page flow and cause elements that were underneath it to 'jump' up.
More issues can arise with page resize, since the menu items of the nav bars can sometimes overflow into a second row (the jump gets bigger when this happens).
Just thought I'd let yall know. I fixed ours by adding (or removing) a new div from the position the nav bar previously occupied via bootstrap affix events.

**Comment by cjg89** [comment]
Hey, thanks for the heads up!  We'll have a fix for this released in v2.1.0.

**Comment by cjg89** [comment]
Fix for this has been tagged in v2.1.0.
